### ISSUE TITLE
[Bug] <title>Arbitration disappear

### ISSUE THREAD

**Issue by wellplayyyyyy** [WFCD/navis#109]
### Describe the bug

In this update cant see Arbitration information ,is it normal

### How to Reproduce

1.open the app
2.
3.
...

### Expected Behavior

I can see what Arbitration now

### What platform are you using Navis on

Android

### Platform Version

Android11

### Cephalon Navis version

2.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
that would be because there's no arbitration data right now

**Comment by TobiTenno** [comment]
Basically not a bug, it's supposed to do this when there's nothing to show.

**Comment by SlayerOrnstein** [comment]
Yup, some rotate information and others disappear entirely. So like alerts arbitration disappear when they finish.
