### ISSUE TITLE
[Feature] Set time for notification

### ISSUE THREAD

**Issue by Hadarios** [WFCD/navis#115]
### Describe the feature you would like.

I think it could be nice to be able to set the hours when you want to receive notifications. 
For example, I don't want to receive notifications when I'm at work, but I want to get them at home, so I'd set the notifications to be sent from 6:30PM to 12AM.

**Comment by SlayerOrnstein** [comment]
What Android version are you using?

**Comment by SlayerOrnstein** [comment]
So looks like Android already has something baked into the system with this if you leverage "Bed time" and Do not disturb
