### ISSUE TITLE
[Feature] Steel Path Incursions & Syndicate Missions

### ISSUE THREAD

**Issue by AstroPenguan** [WFCD/navis#128]
### Is your feature request related to a problem?

Even though this misions are not part of the most relevant ones, they still are useful for some players. 

### Describe the feature you would like.

- Being able to track down the daily steel path incursions
- Being able to select your syndicate(s) of preference and track down missions of them, plus a quick guide/tutorial of how many syndicate meddllions are hidden in e/o based on mission type

**Comment by SlayerOrnstein** [comment]
Although DE exposes the node the syndicate mission is on they don't tell you what mission type it is. This is the same issue with steel path I believe.

**Comment by TobiTenno** [comment]
moreso with steel path, they don't expose anything for that

**Comment by AstroPenguan** [comment]
So... Then it is not gonna be easy to add these features right? Pretty much a shame but if it is like this we can do nothing I guess.

**Comment by SlayerOrnstein** [comment]
Best I can do is implement the new endpoints as beta features.

**Comment by AstroPenguan** [comment]
Thanks, I was sure i missed something but yeah, it was Zariman Bounties, about sp incursions, dont worry, take your time.

**Comment by SlayerOrnstein** [comment]
wait so steel path incursions aren't a thing anymore?

**Comment by SlayerOrnstein** [comment]
Yeah so looks like incursions aren't a thing anymore, so marking this as complete.

**Comment by SlayerOrnstein** [comment]
Yeah so looks like incursions aren't a thing anymore, so marking this as complete.
