### ISSUE TITLE
Navis not switching platforms

### ISSUE THREAD

**Issue by GamerMan27** [WFCD/navis#136]
I play on PS4, and wanted an app that would help we with tracking events on the game without booting it up. So I install the app, boot it up, and go to settings and click the PS4 symbol. Nothing changes other than PS4 is now blue, instead of grey. I'm using a Motorola G Pure, with 3 gigabytes of RAM and 32 gigs of ROM. My Operating system seems to be android version 11.

**Comment by SlayerOrnstein** [comment]
All fixed
