### ISSUE TITLE
[Feature] Show element rotation of melee tenet weapons

### ISSUE THREAD

**Issue by Diriangen71** [WFCD/navis#156]
### Is your feature request related to a problem?

No

### Describe the feature you would like.

Just have a fast view of the element rotation of tenet melee weapons that are active in that specific time, that weapons can be bought from Ergo Glast

### Additional context

Ergo Glast sell melee weaposn that every certain time change base element un a rotation, i want yo view wich element si he selling un every weaposn he sell every rotation without have to go un the Game.

**Comment by TobiTenno** [comment]
not possible with the data we have available. the element rotation is not set.
