### ISSUE TITLE
[Feature] In the Codex, make Relics interactable to show where they drop and at which rate

### ISSUE THREAD

**Issue by CapoFantasma97** [WFCD/navis#160]
### Is your feature request related to a problem?

The codex system you implemented in the app is fantastic. Searching for an item (example Strun Prime) provides which components it's made of, and tapping on those components shows where they drop.

In the case of prime components however, it only shows which relics drop them but not in which missions to obtain said relics.
And searching for the specific relic doesn't provide with any valuable information, just a blank page.

### Describe the feature you would like.

Being able to see where the Relics drop from, at which chance and what would be the most efficient way (e.g. do this mission until x rotation, extract, repeat), would be very useful and make the process of obtaining specific prime sets much easier. An app called [Lootr for Warframe](https://play.google.com/store/apps/details?id=com.ogg.technologies.warframerewards) works in a similar way.

UI wise, it would also be cool to be able to tap on relics inside the components pages to get redirected to the relic page for information on where the relic drops.

It might also be a good idea to unify the relic variants (intact, exceptional, flawless, radiant) into a single page. The variants could be shown similarly to how components are shown on craftable items, and tapping on them would redirect to information specific only to that variant (drop chances of the contained items).

### Additional context

Strun Prime > tap on barrel > list of relics with drop chances > tap on Axi N8 Intact > Axi N8 codex page with drop rates by mission and most efficient rotation strategy > tapping on the Intact icon in the Axi N8 page shows its contents with the items' rarities

**Comment by SlayerOrnstein** [comment]
I can definitely look into adding something like this.

**Comment by SlayerOrnstein** [comment]
>Being able to see where the Relics drop from, at which chance and what would be the most efficient way (e.g. do this mission until x rotation, extract, repeat), would be very useful and make the process of obtaining specific prime sets much easier. An app called [Lootr for Warframe](https://play.google.com/store/apps/details?id=com.ogg.technologies.warframerewards) works in a similar way.

@TobiTenno is sorting by drop chance that same as this?

**Comment by TobiTenno** [comment]
yeah, pretty much. same thing as genesis' `/whereis`

**Comment by SlayerOrnstein** [comment]
@CapoFantasma97 does that work for you and then later on we can look into doing something more with it. Probably don't need to remove the relic types since they are what show up in Warframe items and I would rather keep it untouched, what I can do is figure out the formula (if not already available) and figure out a way to make a UI where you can see the drop chance increase per type.

**Comment by CapoFantasma97** [comment]
> @CapoFantasma97 does that work for you and then later on we can look into doing something more with it. Probably don't need to remove the relic types since they are what show up in Warframe items and I would rather keep it untouched, what I can do is figure out the formula (if not already available) and figure out a way to make a UI where you can see the drop chance increase per type.

Maybe I'm missing something, but I don't see anything different. I downloaded from https://github.com/WFCD/navis/actions/runs/3036727134

**Comment by CapoFantasma97** [comment]
I also noticed that the list of relics for a given component are listed from the least chance of dropping first, which is weird lol.

**Comment by SlayerOrnstein** [comment]
I actually haven't pushed the latest stuff yet

**Comment by SlayerOrnstein** [comment]
@CapoFantasma97 still working on the second part but for now the dev builds will now display drop locations and rates when you search them up in the codex. Turns out it was bug...

**Comment by CapoFantasma97** [comment]
Absolutely fantastic, I love it.

Another useful detail that might be added: a note for vaulted relics.

Not vaulted relics work correctly in that a list of mission with their rotation and drop chance is shown. But vaulted relics of course don't have any drops section, so they remain with an empty page. Users who don't realize this might be confused and not understand that's a vaulted relic they're dealing with.

**Comment by SlayerOrnstein** [comment]
Yeah that was gonna be a whole other commit because I wanted to see if anything else had a similar thing
