### ISSUE TITLE
Entrat Bounties swapped.

### ISSUE THREAD

**Issue by gbravery** [WFCD/navis#191]
Looks like Entrati Isolation Vault A and B are swapped.

I.e. the level and rewards for A is being labelled as B, and vice versa.

**Comment by gbravery** [comment]
![Screenshot_20220925-123009](https://user-images.githubusercontent.com/28046548/192141181-44de4b79-f5f4-46d1-969b-35f811c164a1.png)

**Comment by TobiTenno** [comment]
Levels and the reward strings come from DE's data, so without a snapshot of that at the same moment, we can't do anything to fix the API

**Comment by SlayerOrnstein** [comment]
Closing as a DE issue then. I'll see if I can grab a snapshot or two of this to help out.
