### ISSUE TITLE
Notifications for planet rotations not working

### ISSUE THREAD

**Issue by xLuffiy** [WFCD/navis#29]
**Describe the bug**
In the settings I have tried both checkmarking and unchecking the day/ night cycle for all planets and none of them are pushing notifications when the cycle approaches.

**To Reproduce**
Galaxy S10 phone
Check/uncheck cycle notifications

**Expected behavior**
If I understand correctly, it should be pushing a notification outside the app to alert me for approaching day/night on a planet I choose.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android
 - Version: 9

**Comment by SlayerOrnstein** [comment]
what is your proffered platform, i.e. pc, ps4

**Comment by xLuffiy** [comment]
> what is your preferred platform, i.e. pc, ps4

PC

**Comment by SlayerOrnstein** [comment]
alright I'll take a look, I honestly thought I was just because I work on the app so I don't always have a persistent setting for myself so I never realized it.

**Comment by SlayerOrnstein** [comment]
@xLuffiy alright so I solved the issue with the app itself not receiving notifications but the API is going through a phase so I'm trying to workaround anything that might end up non-existent before I release a build

**Comment by xLuffiy** [comment]
Awesome, I did see the test notification you pushed out earlier. Sounds
like you have a good idea of what's going on :)

Thank you for looking into this.

**Comment by SlayerOrnstein** [comment]
@xLuffiy heads up a beta build is going up in a few hours with the notification fix along with a bunch of other fixes, if you still don't receive notifications for planet rotations you'll have to toggle platforms from PC to any random one and back to PC.

**Comment by xLuffiy** [comment]
I just noticed I needed to join the beta to get the update. I'll let you
know in the morning if I have any issues.

**Comment by xLuffiy** [comment]
So I tested it and still not working. I tried what you said, changing platform back and forth, I also deleted app data, app cache, and did both checked / unchecked filters.

**Comment by SlayerOrnstein** [comment]
According to Google play console the beta build is still being processed if
your app version starts with 1.2.21 then I'll keep taking a look if not
then all we can do is wait till Google finishes processing it.

Will probably upload the release to GitHub's release page if it hasn't
finished processing by the time I get home.

**Comment by SlayerOrnstein** [comment]
@xLuffiy alright Google is still processing so I uploaded it to the release page of GitHub [here`](https://github.com/WFCD/navis/releases/tag/v1.2.21).

**Comment by xLuffiy** [comment]
Either way is fine. There is no rush. I'm happy to test it for you when
it's available.

**Comment by xLuffiy** [comment]
Good news! It got pushed out and it looks like it is working just fine.

**Comment by SlayerOrnstein** [comment]
That's great news, gonna do a last round on a build and push it out to stable.
