### ISSUE TITLE
[Bug] <titre> speak frensh

### ISSUE THREAD

**Issue by Yobie88** [WFCD/navis#307]
### Describe the bug

La langue française n’est pas prise en charge 
![C7070B12-6D27-4DC8-84E7-502A0EB88775](https://user-images.githubusercontent.com/131736265/234170436-5375c936-3e85-4270-86ff-a0652f91e161.png)
![9B8D12F8-D0C4-452E-A9EC-1C65AB8A763E](https://user-images.githubusercontent.com/131736265/234170437-c5adbf78-a841-4e78-99e3-7596d7273d66.png)

### How to Reproduce

1. Seulement la langue FR bug
2.
3.
...

### Expected Behavior

La langue frensh ne charge pas 

### What platform are you using Navis on

iOS

### Platform Version

16

### Cephalon Navis version

Dernière mise à jour 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SlayerOrnstein** [comment]
Ainsi, lorsque j'ai ajouté la prise en charge de la langue, j'ai ajouté que l'application elle-même la prenne en charge, si cela a du sens ?

Fondamentalement, même si l'application n'affiche pas le français, les informations extraites de l'API le sont.

J'utilise Google Translate donc désolé si le contexte traduit est désactivé.

Vous pouvez toujours vous porter volontaire pour aider à traduire l'application en français.
