### ISSUE TITLE
Notification before day or night

### ISSUE THREAD

**Issue by ILynxIl** [WFCD/navis#31]
While notifying when it just turns is good but your doing something a 5 or 10 before notification would so u could load in.

**Comment by SlayerOrnstein** [comment]
Sure I can take a look at it in a bit, 10 mins sounds better gives you time to make a squad

**Comment by ILynxIl** [comment]
Thank you. It would be a really nice addition.
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 9/1/19, 4:28 PM Orn <notifications@github.com> wrote:
Sure I can take a look at it in a bit, 10 mins sounds better gives you time to make a squad

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WFCD/navis/issues/31?email_source=notifications\u0026email_token=ANBXXZX7DNRFWDDE3FISTULQHQXW5A5CNFSM4ISU4UBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5UK6NI#issuecomment-526954293",
"url": "https://github.com/WFCD/navis/issues/31?email_source=notifications\u0026email_token=ANBXXZX7DNRFWDDE3FISTULQHQXW5A5CNFSM4ISU4UBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5UK6NI#issuecomment-526954293",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SlayerOrnstein** [comment]
alright you should start getting cetus day/nght notifications 10 mins early

**Comment by SlayerOrnstein** [comment]
@ILynxIl you should now be receiving Cetus day/night notifications 10 mins before the end
