### ISSUE TITLE
Arbitration

### ISSUE THREAD

**Issue by SlayerOrnstein** [WFCD/navis#32]
Want to add Arbitration so I'll leave this open to keep track of it, if anyone has a UI design they want to shoot out let me know. I myself don't really have anything in mind just going with what looks good in my head.

**Comment by TobiTenno** [comment]
🤔 maybe something simply like sorties?

**Comment by SlayerOrnstein** [comment]
![Screenshot_20191020-171128_Navis 1](https://user-images.githubusercontent.com/6075693/67166421-42383a00-f35d-11e9-95df-c93db39e7676.png)

This is what i thought up

**Comment by TobiTenno** [comment]
yeah, that looks fantastic

**Comment by MrHallows** [comment]
> ![Screenshot_20191020-171128_Navis 1](https://user-images.githubusercontent.com/6075693/67166421-42383a00-f35d-11e9-95df-c93db39e7676.png)
> 
> This is what i thought up

Do you have the Arbitration Drone icon? I think that if it replaced the Arbiters of Hexis icon, it would make it a bit more clear that, that tile is for Arbitrations. If you like the idea, but don't have the icon, I'd be happy to create one in SVG format for you.

**Comment by SlayerOrnstein** [comment]
Well I don't mind, I'm rewriting it as it is and along with it the Ui. It would also be nice to use the skyboxes a bit less. The new one is more minimal but it uses the same icon is you want to see it and have more ideas, so long as it's within the API's abilities.

**Comment by SlayerOrnstein** [comment]
@MrHallows the reason for it is the way I handle loading a skybox is dependent on the node, and with localization it gets a bit hard. when there is like maybe a few fissures/invasions loading them even from network it's easy but we all know at times there ends up being around ~3 node per era, loading that many at least for me has cause some jank. 

I like them too which is why I'm doing tweaks in this new version to see if I can optimize it a bit more but the speed comes and goes on my phone.

**Comment by MrHallows** [comment]
@SlayerOrnstein Oh, okay. Fair point. Wouldn't loading the skyboxes directly as local assets cause less jank? Also, how exactly do images play into localisation? I've never encountered that before; only with textual content.

**Comment by TobiTenno** [comment]
Because the text of the node is localized when it's received by clients, there's no "node key" as of yet

**Comment by SlayerOrnstein** [comment]
@MrHallows I match the node to the name of the skybox, and having all the assets including their localizations increases the size of the APK. Not sure how it works with appbundle though.

**Comment by MrHallows** [comment]
Ah, I see. So, I may be off base here as I don't have very much experience with localisation, but couldn't you use JSON or an array to store the string for each localised node name (or planet/region name, rather), then run a comparison with the JSON object/array to match it to the appropriate file name (in English)? That way only one copy of each skybox is necessary.

**Comment by SlayerOrnstein** [comment]
Hm well, I don't really have much experience with coding in general so I always assumed there was a better way for it and never made much on that idea. In my head I thought of something like this?

```json
"Earth": [translations],
"Venus": [translations]
...
``` 

and then just find which one contains the translations?

**Comment by MrHallows** [comment]
@SlayerOrnstein Yes, that is exactly how I was imagining it structured, too. Iterating through those to match the translation to the respective planet name would take a minimal amount of time, then all you'd have to do is set the skybox image based on the returned planet name.

**Comment by SlayerOrnstein** [comment]
Yeah I can do that, might do it for the next version since there's only a few things left, and majority of the core features are already done.
