### ISSUE TITLE
Resource notifications not working

### ISSUE THREAD

**Issue by Fmagdi** [WFCD/navis#42]
While all direct notifications (based on check boxes in settings window) are working properly, those behind a secondary menu (in my case, Resources) are not firing any notifications when the checked resource has an invasion that rewards it (I have forma, exilus adapter, orokin catalyst, and orokin reactor selected) 

To confirm notifications are otherwise working, I have Baro, world cycles, Sentient outpost, rare alerts, and sortie ticked, all providing notifications properly. 

I also checked if any category of notifications is disabled for Navis at the Android level. Notifications are On, notification dot is On, only one category is shown "Miscellaneous" and it is ticked. 

This behaviour is consistent both on normal and Beta (I tried beta hoping it would work there, but no luck), and on different releases (I've been using Navis for many months now, updating regularly, but the issue is persistent). 

- Open settings
- Choose "Resources"
- Tick forma, exilus adapter, orokin catalyst, and orokin reactor
- Press back on mobile / click "Dismiss" / click outside resource list (behaviour was repeatable with all 3
- Open Resources list again to confirm the items are still ticked. They are.
- Wait for an invasion that rewards any of the items. When that happens, there is no notification 

**Expected behavior**
When an invasion rewarding one of the ticked resources is available, a notification is shown for it. 

**Screenshots (optional)**

**Smartphone (please complete the following information):**
 - Device: Oneplus 5T
 - OS: OxygenOS (Android 9)
 - Version: 9.0.10

**Additional context**

**Comment by Fmagdi** [comment]
Three more things I forgot to mention:
- While Cycles and Acolytes use the same list system as Resources as I just realised after looking again at the settings, their notifications are working properly but not the resources. My apologies for the misinformation.
- I have also updated the drop table just in case it could be related. That didn't fix the issue.
- I have tried removing all ticks from the resources, restart the app, then tick them again. Issue still persisted.

**Comment by SlayerOrnstein** [comment]
So just resource notifications don't work?

**Comment by Fmagdi** [comment]
Yes, the rest is working normally.

**Comment by SlayerOrnstein** [comment]
Well I'm going to keep looking into it, but I just got notifications for both Fieldron and Detonite.

**Comment by Fmagdi** [comment]
To be honest I didn't try Dentonite or Feildron, as I only cared about the orokin catalyst/reactor, exilus adapter, and forma. I just ticked Fieldron and Dentonite to check and will update you with the results.

**Comment by SlayerOrnstein** [comment]
I mean I'll keep looking but those are pretty rare invasions. I've been working on the next version of Navis and finishing nightwave, so I can't really say for certain if there was even one of those within the past to weeks

**Comment by Fmagdi** [comment]
There was a forma one within the past two weeks (Grinneer vs Corpus), but yes I totally understand the rarity of these alerts makes catching/testing an issue quite difficult. If I manage to log while one is up I'll notify you if that helps.

Also to update you, i tested ticking dentonite and feildron and their notifications came without issues. I'll also try the weapon parts/blueprint invasions to get a complete picture and better define the issue limits.

**Comment by SlayerOrnstein** [comment]
Notifications are sent within 2 - 3 mins of them appearing as to avoid duplicates when caching is cleared up. It's possible that if a failure to connect to the API within that window, failed then it just wouldn't send it, regardless of whether it was cached it not.

**Comment by SlayerOrnstein** [comment]
Alight I found the problem a fix is going out server side. Everything should be smoother from here on out.

Will keep this open till the next reactor/catalyst alerts to see if it all worked out. @Fmagdi

**Comment by Fmagdi** [comment]
Thank you, I really appreciate it. I can imagine how hard it is to debug a problem with such a rare situation.

**Comment by SlayerOrnstein** [comment]
Yeah my mistake was reading the wiki and thinking "yeah it's probably just the built reactor/catalyst".

**Comment by Fmagdi** [comment]
Forma and Orokin reward invasions produced a notification today. Thanks you sooo much for your investigation and effort. Makes a great tool even better. 👍👍
