### ISSUE TITLE
Slight Time Difference in Arbitration Countdown Timer

### ISSUE THREAD

**Issue by MrHallows** [WFCD/navis#56]
**Describe the bug**
There appears to be about a ~3m28s difference between the in-game and in-app countdown timer for the active Arbitration mission, with the in-app timer showing ~3m28s more time left than the in-game timer.

**To Reproduce**
Compare the in-game timer to the in-app timer.

**Expected behavior**
You should notice the aforementioned time difference.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S4
 - OS: Android
 - Version 5.0.1

**Comment by SlayerOrnstein** [comment]
Well the app has around the same time give or take ~2s on Warframe hub, so this may be related to the api @TobiTenno ?

**Comment by TobiTenno** [comment]
Yeah, that'd be because all the sources that provide it are guessing. We get it from semlar, who gets it from the games' ee.log, so there's bound to be a bit of drift.

**Comment by SlayerOrnstein** [comment]
Yeah I can't do anything to work around that @MrHallows

**Comment by MrHallows** [comment]
Oh, that makes sense. Thank you both for your prompt responses and no worries at all. I appreciate you both very much for all of the awesome work you've done for the Warframe community.
