### ISSUE TITLE
Mislabeled Field?

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/navis#65]
**Describe the bug**
[I18n vague string](https://navis.t.warframe.gg/translate/cephalon-navis/72/en-ru#79002)

**To Reproduce**
misplaced, not something repro-able

**Expected behavior**
should be cetus night, given the cotnext?

**Screenshots (optional)**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SlayerOrnstein** [comment]
Yup fixed it
