### ISSUE TITLE
Notifications for specificc types of fissures 

### ISSUE THREAD

**Issue by F1ERCEFR0G** [WFCD/navis#71]
First off I love your work, the app is amazing
I think something that would be cool would be being able to turn on notifications for specific mission types such as the endless fissures. That way I could turn notifications on for like, survival/defense/excavate/disruption
I'm not really sure how to do coding, so unfortunately I'm not sure how to help. Thanks again for the awesome app! - android user

**Comment by SlayerOrnstein** [comment]
It's currently out on beta, give it a bit to roll out to production though. if not you can always just get it [here](https://github.com/WFCD/navis/releases/tag/v1.9.0). Any phone from the pass 2-3 years are arm64 so you should be fine with that.
