### ISSUE TITLE
Drop percentages off by x100

### ISSUE THREAD

**Issue by Neo-Desktop** [WFCD/navis#80]
![Screenshot_20201213-175244](https://user-images.githubusercontent.com/321592/102032038-9fb2f580-3d6c-11eb-9acb-3faa77c71f73.png)
According to the drop tables from [Warframe PC Drops](https://n8k6e2y6.ssl.hwcdn.net/repos/hnfvc0o3jnfvc873njb03enrf56.html) the drop percentages should be moved over by 2 decimal places.

Please advise.

**Comment by SlayerOrnstein** [comment]
Which item are you looking at? So I can see what the correct drop rates are.

**Comment by Neo-Desktop** [comment]
I was taking a look at `Ivara Systems Blueprint` in that particular screen shot
![ivara drop](https://user-images.githubusercontent.com/321592/102121069-3d073b80-3df8-11eb-869a-19387285e15f.png)

Am I misinterpreting what the drop chance percentages are (i.e. is this intentional?) or should they be reflecting what I'm highlighting

**Comment by SlayerOrnstein** [comment]
Well I display it as I receive it from the API, I remember the was a reason for it but I can't remember where I saw the explanation for it. @TobiTenno I wanna say I say you pussy it on discord but I can't find it.

**Comment by TobiTenno** [comment]
If you pull it straight from the API, its represented fractionally, whereas the drop site displays percentage. We might wanna change the app to do the calc to get it as a percent.

**Comment by TobiTenno** [comment]
I'm happy to go write the fix since I was unclear

**Comment by TobiTenno** [comment]
There are some things that look like totally different numbers because there's sometimes a % to drop something and a % inside that to drop the specific item, and the API returns the resultant chance

**Comment by SlayerOrnstein** [comment]
So basically I want what I want to do is `drop.chance * 100` ?

**Comment by SlayerOrnstein** [comment]
![Screenshot_1607980054](https://user-images.githubusercontent.com/6075693/102135856-92f2d800-3e26-11eb-9c84-ac9b9a451a2a.png)

Okay seems I got it

**Comment by TobiTenno** [comment]
yay! i just got my local setup updated, so i'm a slow.

**Comment by SlayerOrnstein** [comment]
Fix should be out in a few hours
