### ISSUE TITLE
Warframe market intergration

### ISSUE THREAD

**Issue by SlayerOrnstein** [WFCD/navis#82]
**Is your feature request related to a problem? Please describe.**
Not related to any problems.

**Describe the solution you'd like**
Having a list of sells/buys of a specific tradable item under an item's codex entry. This would also work out to help with riven mod pricing since DE's riven data is as helpful as having active trade data with riven stats. This would be just a limited thing, I don't plan on integrating being able to buy or sell from within the app, just a small list of recent orders.

**Describe alternatives you've considered**
Nothing else is being considered.

**Additional context**
Just seems like something nice to have for people. Especially for newer Tenno.

**Comment by KerstinMaur** [comment]
I like this idea. 👍
