### ISSUE TITLE
Wrong Fissure Missions shown 

### ISSUE THREAD

**Issue by Brocki1704** [WFCD/navis#83]
I activated PS4 but getting shown the wrong fissure missions and also to many missions are shown(+19 missions)

**Comment by TobiTenno** [comment]
could you provide screenshots and details on version, device, etc?

**Comment by Brocki1704** [comment]
![Screenshot_20210113-204956](https://user-images.githubusercontent.com/77406805/104503292-26175d00-55e1-11eb-9796-b9f15bfd205a.jpg)
![Screenshot_20210113-204956](https://user-images.githubusercontent.com/77406805/104503296-2b74a780-55e1-11eb-8829-ac593f923b6e.jpg)
![Screenshot_20210113-204538__01](https://user-images.githubusercontent.com/77406805/104503300-2c0d3e00-55e1-11eb-8019-f0f870b05786.jpg)
![Screenshot_20210113-204549__01](https://user-images.githubusercontent.com/77406805/104503302-2ca5d480-55e1-11eb-933a-b40093d97514.jpg)
![Uploading IMG_20210113_204646.jpg…]()

**Comment by Brocki1704** [comment]
![Uploading IMG_20210113_204646.jpg…]()

**Comment by SlayerOrnstein** [comment]
Does it still do it after you restart the app?

**Comment by Brocki1704** [comment]
This is the first thing I tried... YES
New installation doesn't work too

**Comment by Brocki1704** [comment]
The Daily quest is also buggy

**Comment by TobiTenno** [comment]
do you mean sortie?

**Comment by Brocki1704** [comment]
1. The Version is on the first picture 😑
2. Yeah I mean sortie

**Comment by SlayerOrnstein** [comment]
Yeah i tired I can reproduce the problem you're having, gonna keep trying but as of now I can't pin point what's going on

**Comment by SlayerOrnstein** [comment]
@Brocki1704 are you still getting the same problem or did it fix itself, because I've been trying and switching platforms every so often and I have yet to reproduce it.

**Comment by Brocki1704** [comment]
Yes/No the Fissure mission works right but now the Probleme changed to
Invasion Missions. I changed the platform only after the reinstall

Ornstein <notifications@github.com> schrieb am Do., 14. Jan. 2021, 17:32:

**Comment by SlayerOrnstein** [comment]
oh okay I see it now, @TobiTenno a negative completion is considered done correct?

**Comment by TobiTenno** [comment]
Like completed: false? No, that should be ongoing..

Should just be able to check completed: true

**Comment by SlayerOrnstein** [comment]
ah that works

**Comment by SlayerOrnstein** [comment]
I assume that fissure.expired works the same way then @TobiTenno ?

**Comment by TobiTenno** [comment]
Yeah

**Comment by SlayerOrnstein** [comment]
Looks like NDK got upgrade in GA's virtual environment and the Android build failed. How fix it in a bit and do another release.

**Comment by SlayerOrnstein** [comment]
@Brocki1704 please wait about 24hr and an update with a fix should be in the play store on the beta line
