### ISSUE TITLE
Label Darvo Deal Paragraph

### ISSUE THREAD

**Issue by KerstinMaur** [WFCD/navis#93]
**Is your feature request related to a problem? Please describe.**
I was not sure about what the paragraph in the screenshot was about. I thought it might be the deal from Darvo but I had to visit him to be sure. 😂

**Describe the solution you'd like**
Maybe there could be a label **Darvo deal** in that paragraph (like **Void trader** in the paragraph above). 🤔

**Describe alternatives you've considered**
I do not see alternatives at the moment. 😳

**Additional context**
![DarvoDeal](https://user-images.githubusercontent.com/32022034/117889272-8d090200-b2b3-11eb-9302-08a4565e785c.jpg)

P.S. Thank you so much for this helpful and wonderful app! 👍

**Comment by SlayerOrnstein** [comment]
Alright I'll add this EST morning.

**Comment by SlayerOrnstein** [comment]
Should be out in a few hours if you're on Android, a day or two on iOS.

**Comment by KerstinMaur** [comment]
Thank you so much for the blazing fast implementation!
